export { default as ChatView } from './components/ChatView.vue'
export { default as AgentChats } from './components/AgentChats.vue'
export { default as NewChatPanel, type NewChatRequest } from './components/NewChatPanel.vue'
export { default as MessageMarkdown } from '@shared/ui/MessageMarkdown.vue'
export type { ContentBlock } from './components/ChatComposer.vue'
export { useChatStore, statusLabel, statusTone, type ChatSession } from './stores/sessions'
export { modelAndEffort } from './utils/agent-options'
export { default as SuggestMenu, type SuggestItem } from './components/SuggestMenu.vue'
