export { default as FileTree } from './FileTree.vue'
export { default as CodeView } from './CodeView.vue'
export { fileIconName, folderIconName, iconSvg } from './file-icons'
export { highlightLines, languageFor } from './highlight'
export type * from './types'
export { findPattern, findInLine, markHtml } from './find'
export type { FindOptions, TextRange } from './find'
export { parseUnifiedDiff, diffStats, changeBlocks, stripes, diffRows, fileRows } from './diff-model'
export type { DiffHunk, DiffLine, DiffRow, ChangeBlock, StripeKind } from './diff-model'
