import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import { once } from 'node:events';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';

test('analyst MCP, plan references and execution material selection', async () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'plangent-analysis-agent-'));
  process.env.PLANGENT_DATA_DIR = root;
  const { getDb } = await import('../../infrastructure/db/schema');
  const { createProject } = await import('../projects');
  const { createTask, updateTask } = await import('../tasks');
  const { initQueues, getQueue, saveQueue } = await import('./queue');
  const { initSessions, createSession, updateSession, history } = await import('../agent-sessions/sessions');
  const analysis = await import('./analysis');
  const context = await import('./analysis-context');
  const { buildPrompt, planningToolContext } = await import('./prompts');
  const { submitPlan, stopWatchPlanFile } = await import('./plan-file');
  const { parsePlanSteps, getLatestPlan } = await import('./plans');
  const files = await import('./task-files');
  const { mcpRouter, sessionMcpConfig, allowed } = await import('../../infrastructure/mcp/server');
  const { isPlangentToolCall } = await import('../agent-sessions/plangent-tools');
  initQueues(); initSessions();
  const project = createProject({ name: 'Agents', repo_path: root });
  const task = createTask({ project_id: project.id, key: 'AGENT' });
  const other = createTask({ project_id: project.id, key: 'OTHER' });
  const source = analysis.createAnalysisSection({ task_id: task.id, title: 'API', description: 'SOURCE ONLY' });
  analysis.addAnalysisFile(source.id, { name: 'api.json', mime: 'application/json', content: Buffer.from('{"contract":true}') });
  const analyst = createSession({ project_id: project.id, task_id: task.id, agent_id: 'agent-codex', role: 'analyst', policy: 'read-only' });
  updateSession(analyst.id, { status: 'thinking' });
  const app = express(); app.use(express.json()); app.use('/mcp', mcpRouter);
  const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
  const previousUrl = process.env.PLANGENT_URL;
  process.env.PLANGENT_URL = 'http://127.0.0.1:' + (server.address() as { port: number }).port;
  const clients: Client[] = [];
  async function connect(session: typeof analyst) {
    const config = sessionMcpConfig(session, true)[0] as { url: string; headers: { name: string; value: string }[] };
    const client = new Client({ name: 'test', version: '1.0' });
    await client.connect(new StreamableHTTPClientTransport(new URL(config.url), { requestInit: { headers: Object.fromEntries(config.headers.map(h => [h.name, h.value])) } }));
    clients.push(client); return client;
  }
  function value(result: unknown) { return JSON.parse((result as { content: { text: string }[] }).content[0].text); }
  try {
    const client = await connect(analyst);
    assert.deepEqual((await client.listTools()).tools.map(t => t.name), ['get_analysis', 'save_section']);
    assert.deepEqual(allowed({ ...analyst, role: 'executor' }), ['request_help', 'report_progress']);
    assert.ok(!allowed({ ...analyst, role: 'planner' }).includes('save_section'));
    const initial = value(await client.callTool({ name: 'get_analysis', arguments: {} }));
    assert.equal(initial.groups[0].sections[0].files[0].content, undefined);
    assert.match(initial.groups[0].sections[0].files[0].path, /api.json$/);
    assert.match(buildPrompt({ projectName: project.name, taskKey: task.key, purpose: 'analysis', runHistory: [] }), /Start with.*get_analysis/);
    const saved = value(await client.callTool({ name: 'save_section', arguments: { title: 'Findings', description: 'WORKED ONLY' } }));
    assert.equal(saved.section.kind, 'worked'); assert.equal(saved.section.author, 'agent');
    assert.equal(saved.link, '[[findings]]');
    assert.equal(history(analyst.id).at(-1)!.payload.link, saved.link);
    assert.equal((await client.callTool({ name: 'save_section', arguments: { slug: source.slug, title: 'API', description: 'bad' } })).isError, true);
    assert.equal(analysis.getAnalysisSection(source.id)!.description, 'SOURCE ONLY');
    assert.equal((await client.callTool({ name: 'save_section', arguments: { slug: source.slug, title: 'API', description: 'SOURCE ONLY', source_requested: true } })).isError, undefined);
    const foreign = analysis.createAnalysisSection({ task_id: other.id, title: 'Foreign' });
    assert.throws(() => context.saveAnalystSection(task.id, { slug: foreign.slug, title: 'Foreign', description: '' }), /not found/);
    assert.equal((await client.callTool({ name: 'save_section', arguments: { title: '', description: 'bad' } })).isError, true);
    assert.ok(isPlangentToolCall({ title: JSON.stringify({ title: 'Findings', description: 'Done' }), kind: 'other', rawInput: { title: 'Findings', description: 'Done' } }));
    const plan = '- [ ] Read [[findings]]\n- [ ] Read [[api/api.json]]\n- [ ] Code only';
    submitPlan(task, root, plan, true);
    assert.deepEqual(parsePlanSteps(getLatestPlan(task.id)!.content)[1].analysisLinks, ['api/api.json']);
    const ctx = { projectName: project.name, taskKey: task.key, taskId: task.id, repoPath: root, planContent: getLatestPlan(task.id)!.content, runHistory: [] };
    assert.ok(planningToolContext(ctx).analysis);
    const selected = buildPrompt({ ...ctx, points: ['p1'] });
    assert.match(selected, /WORKED ONLY/); assert.doesNotMatch(selected, /SOURCE ONLY|contract/);
    const attachment = buildPrompt({ ...ctx, points: ['p2'] });
    assert.match(attachment, /api.json/); assert.match(attachment, /"contract":true/);
    assert.doesNotMatch(attachment, /WORKED ONLY|SOURCE ONLY/);
    assert.doesNotMatch(buildPrompt({ ...ctx, points: ['p3'] }), /## Материалы анализа/);
    assert.doesNotMatch(buildPrompt({ ...ctx, points: [] }), /WORKED ONLY|SOURCE ONLY/);
    const before = getLatestPlan(task.id)!.content;
    assert.throws(() => submitPlan(task, root, '- [ ] Bad [[missing]]', true), /Unknown analysis/);
    assert.throws(() => submitPlan(task, root, '- [ ] Bad [[api/missing.json]]', true), /Unknown analysis/);
    assert.equal(getLatestPlan(task.id)!.content, before);
    const empty = createTask({ project_id: project.id, key: 'EMPTY' });
    submitPlan(empty, root, '- [ ] Plain plan', true);
    stopWatchPlanFile(empty.key);
    const planner = createSession({ project_id: project.id, task_id: task.id, agent_id: 'agent-codex', role: 'planner', policy: 'read-only' });
    updateSession(planner.id, { status: 'thinking' });
    const planning = await connect(planner);
    assert.ok(value(await planning.callTool({ name: 'get_plan', arguments: {} })).analysis);
    assert.equal((await planning.callTool({ name: 'submit_plan', arguments: { content: '- [ ] Invalid [[missing]]' } })).isError, true);
    const queue = getQueue(task.id, project.id);
    queue.status = 'running';
    queue.stages = [{ id: 'stage', pauseAfter: false, sessions: [{ id: 'active', points: ['p1'], agentId: 'agent-codex', queueMode: 'execute', permissionPolicy: 'ask', status: 'running' }] }];
    saveQueue(queue, false);
    assert.equal((await client.callTool({ name: 'save_section', arguments: { title: 'Blocked', description: '' } })).isError, true);
    queue.status = 'paused'; saveQueue(queue, false);
    assert.equal((await client.callTool({ name: 'save_section', arguments: { title: 'Allowed', description: '' } })).isError, undefined);
    updateTask(task.id, { status: 'done' });
    assert.equal((await client.callTool({ name: 'save_section', arguments: { title: 'Closed', description: '' } })).isError, true);
  } finally {
    await Promise.all(clients.map(c => c.close()));
    await new Promise<void>(resolve => server.close(() => resolve()));
    if (previousUrl === undefined) delete process.env.PLANGENT_URL; else process.env.PLANGENT_URL = previousUrl;
    stopWatchPlanFile(task.key); files.stopWatchAnalysis(task.id); files.stopWatchAnalysis(other.id);
    getDb().close();
    fs.rmSync(root, { recursive: true, force: true });
  }
});
